import { LegalLayout, LSection, LP, LList, LItem, LSub, LNote } from "@/components/LegalLayout";

export const metadata = {
  title: "Privacy Policy — Interlock",
  description: "How Interlock collects, uses, and protects your personal information.",
};

export default function PrivacyPage() {
  return (
    <LegalLayout
      badge="Legal"
      title="Privacy Policy"
      lastUpdated="May 28, 2026"
    >

      <LP>
        Interlock (&ldquo;we&rdquo;, &ldquo;our&rdquo;, or &ldquo;us&rdquo;) operates the platform available at interlock.xyz. This Privacy Policy explains what personal data we collect, why we collect it, how we use and protect it, and what rights you have over it. By using our platform, you agree to the practices described here.
      </LP>
      <LP>
        This policy applies to all visitors, registered users, and API integrators of Interlock. If you are using Interlock on behalf of a business, &ldquo;you&rdquo; refers to that business and its authorised representatives.
      </LP>

      {/* 1 */}
      <LSection title="1. Information We Collect">
        <LP>
          We collect information you provide directly, information generated by your use of the platform, and technical data sent automatically by your devices.
        </LP>

        <LSub title="1.1 Account and Contact Data" />
        <LList>
          <LItem>Full name and job title</LItem>
          <LItem>Business email address</LItem>
          <LItem>Company name and size</LItem>
          <LItem>Password (stored as a salted cryptographic hash — never in plain text)</LItem>
          <LItem>Billing contact information</LItem>
        </LList>

        <LSub title="1.2 Usage and Platform Data" />
        <LList>
          <LItem>Workflows created, modified, and executed — including names, configurations, and execution counts</LItem>
          <LItem>Quotes requested and pricing parameters set</LItem>
          <LItem>Feature interactions, dashboard navigation paths, and time spent on pages</LItem>
          <LItem>API keys you generate and the calls made against them (request counts, timestamps, endpoints)</LItem>
          <LItem>Customer records and segments you create within the platform</LItem>
        </LList>

        <LSub title="1.3 Workflow Execution Data" />
        <LP>
          When your agents execute workflows through Interlock, we process and store:
        </LP>
        <LList>
          <LItem>Workflow inputs and outputs (which may contain content generated by or submitted to AI models)</LItem>
          <LItem>Token counts and model identifiers from AI provider calls</LItem>
          <LItem>Tool call records, retry counts, and execution durations</LItem>
          <LItem>Cost attribution line items (model fees, tool API costs, human-in-the-loop charges)</LItem>
          <LItem>Outcome verification artifacts — stored as content-addressed blobs on Walrus decentralised storage; only blob IDs and SHA-256 hashes are stored in our Postgres database</LItem>
          <LItem>Attestation payloads and settlement records</LItem>
        </LList>
        <LNote>
          Workflow execution data may contain sensitive business information. You are responsible for ensuring that any data submitted to Interlock workflows complies with applicable laws and does not contain regulated personal data (such as health records or payment card numbers) unless you have obtained the necessary consents and disclosures.
        </LNote>

        <LSub title="1.4 Blockchain and Wallet Data" />
        <LList>
          <LItem>Avalanche wallet addresses you connect or authorise for settlement</LItem>
          <LItem>On-chain transaction hashes, object IDs, and settlement amounts</LItem>
          <LItem>USDC escrow balances and payout records associated with your account</LItem>
        </LList>
        <LNote>
          Blockchain data recorded on the Avalanche network is public and permanent by design. We have no ability to delete or alter any data that has been committed to the Avalanche blockchain.
        </LNote>

        <LSub title="1.5 Technical and Device Data" />
        <LList>
          <LItem>IP address (used for security, rate-limiting, and approximate geolocation at the country level)</LItem>
          <LItem>Browser type and version</LItem>
          <LItem>Operating system and device type</LItem>
          <LItem>Referring URL and exit URL</LItem>
          <LItem>Session identifiers and timestamps</LItem>
          <LItem>Error logs, crash reports, and API response codes</LItem>
        </LList>

        <LSub title="1.6 Cookie and Analytics Data" />
        <LList>
          <LItem>Strictly necessary session cookies (required for login and CSRF protection)</LItem>
          <LItem>Preference cookies (theme, language, display settings)</LItem>
          <LItem>Analytics identifiers used to measure aggregate product usage (no cross-site tracking)</LItem>
        </LList>

        <LSub title="1.7 Communication Data" />
        <LList>
          <LItem>Messages you send us via the contact form, email, or support channels</LItem>
          <LItem>Records of consent for marketing communications</LItem>
        </LList>
      </LSection>

      {/* 2 */}
      <LSection title="2. How We Use Your Information">
        <LP>We use the data we collect for the following purposes:</LP>
        <LList>
          <LItem><strong className="text-white">Service provision</strong> — to create and maintain your account, process workflow executions, execute USDC settlements, and deliver the platform features you have subscribed to.</LItem>
          <LItem><strong className="text-white">Billing and payments</strong> — to calculate GMV-based fees, generate invoices, process subscription charges, and maintain settlement records.</LItem>
          <LItem><strong className="text-white">Security and fraud prevention</strong> — to detect, investigate, and prevent unauthorised access, abuse, and violations of our Terms of Service.</LItem>
          <LItem><strong className="text-white">Product improvement</strong> — to understand how the platform is used, identify bugs, and prioritise features. Analytics are performed on aggregated or pseudonymised data.</LItem>
          <LItem><strong className="text-white">Transactional communications</strong> — to send you account confirmations, settlement notifications, API alerts, and important service updates.</LItem>
          <LItem><strong className="text-white">Support</strong> — to respond to your enquiries, diagnose issues, and provide technical assistance.</LItem>
          <LItem><strong className="text-white">Legal compliance</strong> — to meet our obligations under applicable laws, respond to lawful requests from authorities, and enforce our agreements.</LItem>
          <LItem><strong className="text-white">Marketing (with consent)</strong> — to send product updates, newsletters, and promotional materials where you have opted in. You may unsubscribe at any time.</LItem>
        </LList>
      </LSection>

      {/* 3 */}
      <LSection title="3. Legal Bases for Processing (GDPR)">
        <LP>
          If you are located in the European Economic Area or the United Kingdom, we rely on the following legal bases to process your personal data:
        </LP>
        <LList>
          <LItem><strong className="text-white">Contract performance</strong> — processing necessary to provide the services you have signed up for.</LItem>
          <LItem><strong className="text-white">Legitimate interests</strong> — security monitoring, fraud prevention, product analytics, and improving our services, where these interests are not overridden by your rights.</LItem>
          <LItem><strong className="text-white">Legal obligation</strong> — where we are required to retain or disclose data by applicable law.</LItem>
          <LItem><strong className="text-white">Consent</strong> — for marketing communications and non-essential cookies. You may withdraw consent at any time without affecting the lawfulness of prior processing.</LItem>
        </LList>
      </LSection>

      {/* 4 */}
      <LSection title="4. Sharing and Disclosure">
        <LP>
          We do not sell your personal data. We share data only in the following circumstances:
        </LP>

        <LSub title="4.1 Infrastructure and Service Providers" />
        <LP>
          We engage trusted third-party providers who process data solely on our instructions:
        </LP>
        <LList>
          <LItem><strong className="text-white">Vercel Inc.</strong> — hosting, edge delivery, and serverless compute (United States)</LItem>
          <LItem><strong className="text-white">Neon Inc.</strong> — managed Postgres database (United States)</LItem>
          <LItem><strong className="text-white">Mysten Labs / Walrus</strong> — decentralised blob storage for workflow artifacts (global, content-addressed)</LItem>
          <LItem><strong className="text-white">Ava Labs</strong> — the public Avalanche blockchain network (immutable, globally distributed)</LItem>
          <LItem><strong className="text-white">AI model providers</strong> — if your workflows call third-party model APIs (e.g., Anthropic, OpenAI), those providers receive the content you submit to those models under their own privacy policies. We only see and store the token-level cost metadata.</LItem>
        </LList>

        <LSub title="4.2 Legal Requirements" />
        <LP>
          We may disclose personal data if required to do so by law, court order, or governmental authority, or if we believe disclosure is necessary to protect the rights, property, or safety of Interlock, our users, or the public.
        </LP>

        <LSub title="4.3 Business Transfers" />
        <LP>
          In the event of a merger, acquisition, restructuring, or sale of assets, personal data may be transferred as part of that transaction. We will notify you via email or a prominent notice on our website before your data is subject to a different privacy policy.
        </LP>

        <LSub title="4.4 With Your Consent" />
        <LP>
          We may share data with third parties for other purposes when you have explicitly authorised us to do so.
        </LP>
      </LSection>

      {/* 5 */}
      <LSection title="5. International Data Transfers">
        <LP>
          Interlock is headquartered in Bengaluru, Karnataka, India. Our infrastructure providers operate in the United States and globally. If you are located in a jurisdiction with data transfer restrictions (such as the EU/EEA), please note:
        </LP>
        <LList>
          <LItem>Transfers to Vercel and Neon (US) are conducted under appropriate safeguards, including Standard Contractual Clauses where required.</LItem>
          <LItem>Data written to the Avalanche blockchain and Walrus network is distributed globally and is subject to those networks&rsquo; own properties, which we do not control.</LItem>
        </LList>
      </LSection>

      {/* 6 */}
      <LSection title="6. Data Retention">
        <LList>
          <LItem><strong className="text-white">Account data</strong> — retained for the duration of your account and for two years after closure, to comply with legal obligations and resolve disputes.</LItem>
          <LItem><strong className="text-white">Workflow execution and billing records</strong> — retained for seven years to satisfy financial record-keeping requirements.</LItem>
          <LItem><strong className="text-white">Technical logs</strong> — retained for 90 days, then deleted or anonymised.</LItem>
          <LItem><strong className="text-white">Blockchain data</strong> — permanent; we cannot delete data recorded on the Avalanche network.</LItem>
          <LItem><strong className="text-white">Walrus blobs</strong> — retained for the storage epoch you have committed to; we store the blob ID and hash in our database for as long as needed to support dispute resolution.</LItem>
          <LItem><strong className="text-white">Marketing consent records</strong> — retained until you withdraw consent plus three years.</LItem>
        </LList>
      </LSection>

      {/* 7 */}
      <LSection title="7. Your Privacy Rights">
        <LP>
          Depending on your location, you may have the following rights regarding your personal data:
        </LP>
        <LList>
          <LItem><strong className="text-white">Access</strong> — request a copy of the personal data we hold about you.</LItem>
          <LItem><strong className="text-white">Rectification</strong> — request correction of inaccurate or incomplete data.</LItem>
          <LItem><strong className="text-white">Erasure</strong> — request deletion of your personal data where we have no overriding legal basis to retain it. Note: on-chain data cannot be erased.</LItem>
          <LItem><strong className="text-white">Restriction</strong> — request that we restrict processing while a dispute about accuracy or legal basis is resolved.</LItem>
          <LItem><strong className="text-white">Portability</strong> — receive a machine-readable copy of data you have provided to us.</LItem>
          <LItem><strong className="text-white">Objection</strong> — object to processing based on legitimate interests or for direct marketing.</LItem>
          <LItem><strong className="text-white">Withdraw consent</strong> — where processing is based on consent, withdraw it at any time without affecting prior lawful processing.</LItem>
        </LList>
        <LP>
          To exercise any of these rights, email us at{" "}
          <a href="mailto:privacy@interlock.xyz" className="text-white underline underline-offset-2">
            privacy@interlock.xyz
          </a>
          . We will respond within 30 days. We may need to verify your identity before acting on your request.
        </LP>

        <LSub title="California Residents (CCPA / CPRA)" />
        <LP>
          California residents have the right to know what personal information we collect and how it is used or shared, the right to delete personal information (subject to exceptions), the right to correct inaccurate information, and the right to opt out of the sale or sharing of personal information. We do not sell personal information. To make a CCPA request, contact us at privacy@interlock.xyz.
        </LP>
      </LSection>

      {/* 8 */}
      <LSection title="8. Cookies">
        <LP>
          We use cookies and similar technologies as described in Section 1.6. You may control cookies through your browser settings. Disabling strictly necessary cookies will prevent you from logging in. Analytics cookies can be declined without affecting core functionality. We honour Do Not Track signals where technically feasible.
        </LP>
      </LSection>

      {/* 9 */}
      <LSection title="9. Data Security">
        <LP>
          We apply appropriate technical and organisational measures to protect your data, including TLS 1.3 for data in transit, AES-256 encryption for data at rest, cryptographic hashing for passwords, and access controls following the principle of least privilege. See our{" "}
          <a href="/security" className="text-white underline underline-offset-2">
            Security page
          </a>{" "}
          for a full description of our security practices.
        </LP>
        <LP>
          Despite these measures, no system is completely secure. In the event of a data breach that is likely to result in risk to your rights, we will notify you and relevant supervisory authorities within 72 hours of becoming aware.
        </LP>
      </LSection>

      {/* 10 */}
      <LSection title="10. Children's Privacy">
        <LP>
          Interlock is a business-to-business platform intended solely for use by individuals aged 18 or older acting on behalf of a business entity. We do not knowingly collect personal data from anyone under 18. If you believe a minor has provided us with personal data, contact us at privacy@interlock.xyz and we will delete it promptly.
        </LP>
      </LSection>

      {/* 11 */}
      <LSection title="11. Changes to This Policy">
        <LP>
          We may update this Privacy Policy from time to time. We will notify you of material changes by posting a prominent notice on our website and, where we have your email, by sending you a notification at least 14 days before the change takes effect. Your continued use of the platform after the effective date constitutes acceptance of the revised policy.
        </LP>
      </LSection>

      {/* 12 */}
      <LSection title="12. Contact Us">
        <LP>
          If you have questions, concerns, or requests regarding this Privacy Policy or your personal data, please contact:
        </LP>
        <LList>
          <LItem>
            <strong className="text-white">Privacy enquiries:</strong>{" "}
            <a href="mailto:privacy@interlock.xyz" className="text-white underline underline-offset-2">
              privacy@interlock.xyz
            </a>
          </LItem>
          <LItem>
            <strong className="text-white">General contact:</strong>{" "}
            <a href="mailto:team@interlock.xyz" className="text-white underline underline-offset-2">
              team@interlock.xyz
            </a>
          </LItem>
          <LItem>
            <strong className="text-white">Postal address:</strong> Interlock, Bengaluru, Karnataka, India
          </LItem>
        </LList>
      </LSection>

    </LegalLayout>
  );
}
